### ISSUE TITLE
beforeBundle not working

### ISSUE THREAD

**Issue by qlaffont** [unplugin/unplugin-imagemin#100]
### Steps to reproduce

- Create a repo with this plugin loaded and this config :

```js
imagemin({
        mode: 'sharp',
        beforeBundle: true,
        // Default configuration options for compressing different pictures
        compress: {
          jpg: {
            quality: 50,
          },
          jpeg: {
            quality: 70,
          },
          png: {
            quality: 70,
          },
          webp: {
            quality: 70,
          },
        },
      }),
```

### What is expected?

able to optimize images

### What is actually happening?

[unplugin-imagemin] 📦 📦 Process start with Mode sharp
            ▶ Not Found Image Module,  if you want to use style with image style, such as "background-image" you can use "beforeBundle: false" in plugin config

### System Info

```shell
- Linux (PopOS)
```

### Any additional comments?
Working with solid-start : https://start.solidjs.com/getting-started/project-setup

If I use "beforeBundle" with false ->  
```bash

[Error: ENOENT: no such file or directory, open '/home/quentin/Documents/dev/test/demo-ventes/dist/public/index.html'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/quentin/Documents/dev/test/demo-ventes/dist/public/index.html'
}
```

**Comment by ErKeLost** [comment]
I'll try.

**Comment by ErKeLost** [comment]
hi @qlaffont  I have solved this problem and you can now install v0.5.15 to solve this error.

**Comment by qlaffont** [comment]
confirmed for beforeBundle: false but beforeBundle: true still say that no image module is found

**Comment by ErKeLost** [comment]
BeforeBundle is used to control true to convert images after the bundle is completed. False is for the vite load module, when we represent a new set of image resources, which may need to be integrated into a vite load mode. Now, when we run in load, we do not find the image resources, so we need to manually modify the source code after bundle. I tried earlier today that it can be compiled and compressed normally. Can you provide a warehouse that can be reproduced?

**Comment by qlaffont** [comment]
@ErKeLost after a long debugging period:
- beforeBundle: false don't crash on build but images are not found in dist :thinking: 
- beforeBundle: true, i keep you in touch with the repro

**Comment by ErKeLost** [comment]
I'll check what you said later.

**Comment by qlaffont** [comment]
Any update?

**Comment by ErKeLost** [comment]
I'll try to recreate it today. I'm sorry I've been a little busy lately.

**Comment by ErKeLost** [comment]
@qlaffont hi.  The newly created solid ssr template seems to have some problems. Build will fail. The reason you said that the image resources are not stored in the dist directory may be because there is a problem with the output path acquisition of ssr.

**Comment by qlaffont** [comment]
So you are telling me, at this point we have no solution to use this plugin

**Comment by ErKeLost** [comment]
It can be solved at present, but pnpm create solid build seems to have some problems at present. I failed to build. Can you provide a warehouse that can be reproduced?

**Comment by qlaffont** [comment]
You have the repro here @ErKeLost : https://github.com/qlaffont/solid-start-project

**Comment by ErKeLost** [comment]
I tried beforeBundle false to find the picture in dist after build in your repo.

![image](https://github.com/unplugin/unplugin-imagemin/assets/66500121/e62c7aff-797b-4c8e-bc1c-89318f235fe2)

Did you say that the picture could not be found in dist after setting false?

![image](https://github.com/unplugin/unplugin-imagemin/assets/66500121/b198ddf1-4496-4e28-b6ef-5a33d037d8bd)

I don't know if there's a problem with my understanding, and if it is, please tell me that I will continue to fix this problem, and I found that there is less problem of finding build products in ssr. I'll solve this problem first.

**Comment by qlaffont** [comment]
I have updated the example with the img tag and it doesn't work : https://github.com/qlaffont/solid-start-project/commit/4681c6cf57bd5847da8c8c8d68c571f2ea1b667a

**Comment by qlaffont** [comment]
With `beforeBundle: true` :

```bash
[unplugin-imagemin] 📦 📦 Process start with Mode sharp
            ▶ Not Found Image Module,  if you want to use style with image style, such as "background-image" you can use "beforeBundle: false" in plugin config
✔ Image conversion completed!
```

Image is found in dist but not compressed

**Comment by ErKeLost** [comment]
In the case of url import, you can't find the corresponding module. You can use the module import method first. I will solve this problem as soon as possible.

**Comment by qlaffont** [comment]
I keep the issue until it is possible, because I need to upload image as background sometimes and I need to have these files.

**Comment by qlaffont** [comment]
When do you think you will work on this ? It's kind of critical for me ^^"

**Comment by ErKeLost** [comment]
> When do you think you will work on this ? It's kind of critical for me ^^"

I have been very busy because of my work. I will solve this problem as soon as possible this week.

**Comment by qlaffont** [comment]
@ErKeLost  any update ?

**Comment by ErKeLost** [comment]
> @ErKeLost any update ?

I'm so sorry. I've been too busy at work lately. I don't have time to check it out.

**Comment by ErKeLost** [comment]
The latest version solves all problems, and you can try again if necessary
