### ISSUE TITLE
vite项目，会把public目录下载的图片移到assets目录下

### ISSUE THREAD

**Issue by chenbimo** [unplugin/unplugin-imagemin#112]
### Steps to reproduce

vite 5 + vue3

### What is expected?

放在public目录中的图片，经过压缩后，跑到了assets目录中

### What is actually happening?

放在public目录中的图片，经过压缩后，跑到了assets目录中

**Comment by ErKeLost** [comment]
可以提供一个 demo 么 我这复现不出来 这块逻辑需要重新写一下

**Comment by ErKeLost** [comment]
![image](https://github.com/unplugin/unplugin-imagemin/assets/66500121/11924531-81a3-40c2-bfe9-04a14768452f)

**Comment by chenbimo** [comment]
![image](https://github.com/unplugin/unplugin-imagemin/assets/33003566/e27dbbe3-3d42-428f-97ee-bc9acfea066f)

public里面的logo.png和img/logo.png 都进到assets里面去了，demo的话，得花点时间把复现的代码抽取一下。

**Comment by chenbimo** [comment]
问题解决了，从0.5.15升级到了0.5.18，感谢你们的工作，插件非常有用！

**Comment by ErKeLost** [comment]
嗷嗷 那可能是之前的问题 okok
