### ISSUE TITLE
Could not load the "sharp" module using the darwin-x64 runtime

### ISSUE THREAD

**Issue by yusongh** [unplugin/unplugin-imagemin#114]
### Steps to reproduce

1. Install imagemin
2. Run packaging

### What is expected?

No error reported

### What is actually happening?

<img width="589" alt="image" src="https://github.com/unplugin/unplugin-imagemin/assets/45997005/3e4b53da-4afc-45f9-80b8-708311351505">

### System Info

```shell
Intel Mac OS 14.1
Node v18.12.1
```

**Comment by ErKeLost** [comment]
Follow the prompts to install it, which is not under the control of the plugin. Later, i may consider using sharp and squoosh as development dependencies.

**Comment by yusongh** [comment]
> 按照提示安装即可，不受插件控制。稍后，我可能会考虑使用 Sharp 和 Scoosh 作为开发依赖项。

<img width="830" alt="image" src="https://github.com/unplugin/unplugin-imagemin/assets/45997005/7a39d949-f08e-42c2-aa2e-86e2192b2597">

When used in vitepress, the above error message will appear

**Comment by ErKeLost** [comment]
Can you provide a repo that can be reproduced? I'll try it.

**Comment by yusongh** [comment]
> Can you provide a repo that can be reproduced? I'll try it.

<img width="757" alt="image" src="https://github.com/unplugin/unplugin-imagemin/assets/45997005/4b8e0c6f-e940-4f64-8dbe-c36fa39cf487">

reproduced repo: https://github.com/yusongh/vitepress-imagemin-problem-demo

I did not reproduce the error(https://github.com/unplugin/unplugin-imagemin/issues/114#issuecomment-1925216325) mentioned above in the warehouse, but I reproduced another error. I suspect it is the same type of problem

**Comment by ErKeLost** [comment]
ok i will try it

**Comment by ErKeLost** [comment]
The latest version solves all problems already remove sharp and squoosh support  all node version
