### ISSUE TITLE
support gif image compress

### ISSUE THREAD

**Issue by Alkaidcc** [unplugin/unplugin-imagemin#115]
### What problem does this feature solve?

any plan for supporting gif image compress?

### What does the proposed API look like?

```js
imagemin({
    mode: 'sharp',
    compress: {
      gif: {}
    }
  }),
```

**Comment by ErKeLost** [comment]
Neither squoosh nor sharp supports gif compression, so you may need to consider the cost of supporting this format. Do you have any good suggestions?

**Comment by Alkaidcc** [comment]
Dose sharp not support gif compression? https://sharp.pixelplumbing.com/api-output#gif
Can we use below?
```js
await sharp('in.gif', { animated: true })
  .gif({ interFrameMaxError: 8 })
  .toFile('optim.gif');
```

> Optimal
> The features of mozjpeg and pngquant can be used to optimise the file size of JPEG and PNG images respectively, without having to invoke separate imagemin processes.
> Huffman tables are optimised when generating JPEG output images without having to use separate command line tools like [jpegoptim ](https://github.com/tjko/jpegoptim) and [jpegtran ](http://jpegclub.org/jpegtran/).
> PNG filtering is disabled by default, which for diagrams and line art often produces the same result as [pngcrush ](https://pmt.sourceforge.io/pngcrush/).
> The file size of animated GIF output is optimised without having to use separate command line tools such as [gifsicle ](https://www.lcdf.org/gifsicle/).

**Comment by ErKeLost** [comment]
Oh, I'm so sorry I missed this. I'll add gif compress

**Comment by ErKeLost** [comment]
Sorry to bother you for such a long time. I have done a version of optimization and now I have removed my reliance on sharp and I will not consider supporting gif compression for the time being.

Now there is only one compression method, squoosh, to reduce maintenance costs
