### ISSUE TITLE
Support Node v20

### ISSUE THREAD

**Issue by recallwei** [unplugin/unplugin-imagemin#116]
### Steps to reproduce

Install dep with Node.js v20.10.0:
```bash
pnpm add -D unplugin-imagemin
```

![image](https://github.com/unplugin/unplugin-imagemin/assets/62941121/4e8b866f-a056-4af6-b9cf-eec2a9e228b2)
![image](https://github.com/unplugin/unplugin-imagemin/assets/62941121/f6935911-4c4c-4544-9f31-afab57c53558)

### What is expected?

Support Node v20

### What is actually happening?

Cannot install correctly.

### System Info

```shell
OS: MacOS 
Arch: arm64
Browser: Chorme
```

**Comment by Stryxus** [comment]
This is a [@squoosh](https://www.npmjs.com/package/@squoosh/lib) issue which, is now, abandoned. Squoosh should be removed from the plugin and use Sharp.

**Comment by ryoppippi** [comment]
I want to use it on Node20, so please remove squoosh !!

**Comment by ErKeLost** [comment]
> I want to use it on Node20, so please remove squoosh !!

I checked the code and it has been processed. Although squoosh will still be installed, sharp will be used automatically if it is greater than node 18.  If you get an error when running, please provide more detailed information. Thank you.
