### ISSUE TITLE
Disabling publicDir breaks plugin

### ISSUE THREAD

**Issue by Santana1053** [unplugin/unplugin-imagemin#118]
### Steps to reproduce

I was having getting this plugin to work because I would get an error saying `Error: ENOENT: no such file or directory, open '<path>'`, and when I inspected the file path I noticed that the output directory was in the path twice. I did some debugging and  I discovered the issue is [here](https://github.com/unplugin/unplugin-imagemin/blob/b8e12e36ed767cc6031ad550a19b0f4e168977a5/src/core/sharp.ts#L62), it tries to get the relativePath of the file name based off the publicDir, but in my case I have my publicDir disabled. So the path it was building turned out to be `<projectRoot>/<outDir>/<outDir>/<fileName>`.

### What is expected?

Obtain the relative path of the file without relying on the publicDir.

### What is actually happening?

Disabling publicDir causes outDir to appear twice in file path.

**Comment by ErKeLost** [comment]
Thank you for your question. I'll check it out. The problem will be fixed later.

**Comment by ErKeLost** [comment]
The latest version solves all bugs. You can try to install the latest version. Sorry, the fix was slow.
