### ISSUE TITLE
require() of ES Module ***** not supported.

### ISSUE THREAD

**Issue by FANZHETWO** [unplugin/unplugin-imagemin#128]
### Steps to reproduce

import {defineConfig} from 'vite';
import vue2 from '@vitejs/plugin-vue2';
import legacy from '@vitejs/plugin-legacy'
import compressPlugin from 'vite-plugin-compression';
import path from 'path';
import autoprefixer from 'autoprefixer';
import viteImagemin from 'vite-plugin-imagemin'
import imagemin from 'unplugin-imagemin/vite';
import progress from 'vite-plugin-progress'
import requirePlugin from './plugin/vite-plugin-require-transform';
import commonjs from 'vite-plugin-commonjs';
import config from './buildConfig'
import CopyFilePlugin from "./plugin/vite-plugin-copy-file";
import ZipPlugin from "./plugin/vite-plugin-bunlde-zip";
import ImageCdnPlugin from "./plugin/vite-plugin-image-cdn";
import url from '@rollup/plugin-url';
import {OSS_CDN_ADDRESS} from "./buildConfig/OSS-CDN-IMG/oss-cdn-config";
import { visualizer } from 'rollup-plugin-visualizer';
import Inspect from 'vite-plugin-inspect'

const IS_PRODUCTION = process.env.NODE_ENV === 'production';
console.log(process.env.NODE_ENV)
const ENV_TYPE = config[process.env.NODE_ENV];
const open_visualizer = process.env.npm_config_report;
export default defineConfig(() => {
    return {
        base: "./",
        productionSourceMap: !IS_PRODUCTION,
        plugins: [
            vue2(),
            legacy({
                targets: ['Chrome 64'],
                modernPolyfills: true
            }),
            commonjs(),
            imagemin({
                // Default mode sharp. support squoosh and sharp
                mode: 'squoosh',
                // beforeBundle: true,
                // Default configuration options for compressing different pictures
                compress: {
                  jpg: {
                    quality: 10,
                  },
                  jpeg: {
                    quality: 10,
                  },
                  png: {
                    quality: 10,
                  },
                  webp: {
                    quality: 10,
                  },
                },
              }),
            CopyFilePlugin({
              files: [
                {
                  from: 'CubeModule.json',
                  to: 'dist/CubeModule.json',
                  transform: (content) => {
                    if (!IS_PRODUCTION) {
                        // 对调版本号
                        const cubeModule = JSON.parse(content)
                        const temp = {
                            version: cubeModule.version,
                            build: cubeModule.build,
                        }

                        for (const p in temp) {
                            if (Object.prototype.hasOwnProperty.call(temp, p)) {
                                cubeModule[p] = cubeModule[`test${p[0].toUpperCase()}${p.slice(1)}`]
                                cubeModule[`test${p[0].toUpperCase()}${p.slice(1)}`] = temp[p]
                            }
                        }

                        return Buffer.from(JSON.stringify(cubeModule))
                    } else {
                        return Buffer.from(content)
                    }
                  },
                },
              ],
            }),

            ZipPlugin(),
            progress({
                // format: 'building [:bar] :percent',
                // total: 200,
                // width: 60,
                // complete: '=',
                // incomplete: '',
            }),
            // 构建依赖可视化
            open_visualizer && visualizer({
                open: true,
            }),
            Inspect({
                build: true,
                outputDir: '.vite-inspect'
              }),
        ],
        server: {
            host: '0.0.0.0',
            port: 8080,
            cors: true, //为开发服务器配置 CORS , 默认启用并允许任何源
            strictPort: false, //设为true时端口被占用则直接退出，不会尝试下一个可用端口
        },
        define: {
            $envType: ENV_TYPE,
            global: 'window', // 解决 外部依赖包 global is not defined 问题
        },
        css: {
            postcss: {
                plugins: [
                    autoprefixer({
                        overrideBrowserslist: [
                            "Android 4.1",
                            "iOS 7.1",
                            "Chrome > 31",
                            "ff > 31",
                            "ie >= 8"
                        ],
                        grid: true
                    })
                ]
            },
        },
        resolve: {
            // 配置别名
   
            extensions: ['.vue', '.js', '.json']
        },
        // optimizeDeps: {
        //     include: ['./src/**']
        // },
        build: {
            target: 'es2015',
            assetsDir: 'static',
            // 指定输出路径
            outDir: 'dist',
            // 小于此阈值的导入或引用资源将内联为 base64 编码，以避免额外的 http 请求。设置为 0 可以完全禁用此项
            // assetsInlineLimit: 0, // 默认：4kb 减少http 请求
            // chunk 大小警告的限制
            chunkSizeWarningLimit: 1500,
            //启用/禁用 CSS 代码拆分
            cssCodeSplit: true,
            //设置为 chrome61，以防止 vite 将 rgba() 颜色转化为 #RGBA 十六进制符号的形式。
            cssTarget: 'chrome61',
            //构建后是否生成 source map 文件
            sourcemap: !IS_PRODUCTION,
            //当设置为 true，构建后将会生成 manifest.json 文件
            manifest: false,
            // 设置为 false 可以禁用最小化混淆，或是用来指定使用哪种混淆器
            // boolean | 'terser' | 'esbuild'
            minify: 'terser', //terser 构建后文件体积更小  esbuild 比 terser 快 20-40 倍，压缩率只差 1%-2%
            //默认情况下，若 outDir 在 root 目录下，则 Vite 会在构建时清空该目录。
            emptyOutDir: true,
            //启用/禁用 brotli 压缩大小报告
            reportCompressedSize: false,
            // 预加载
            modulePreload: false, // todo iOS 兼容很差  https://caniuse.com/?search=modulepreload
            terserOptions: {
              compress: {
                drop_console: IS_PRODUCTION,
                drop_debugger: IS_PRODUCTION,
              },
            },
            // 传递给 @rollup/plugin-commonjs 插件的选项。
            // commonjsOptions: {
            //     include: ['./src/**', /node_modules/],
            // },
            rollupOptions: {
                output: {
                    chunkFileNames: 'static/js/[name]-[hash].js', // 自定义命名代码分割中产生的 chunk
                    entryFileNames: 'static/js/[name]-[hash].js', // 指定 chunks 的入口文件模式
                    assetFileNames: (assetInfo) => {
                        const isImage = /\.(png|jpe?g|gif)$/.test(assetInfo.name)
                        // 自定义构建结果中的静态资源名称
                        let filePath = [...assetInfo.name.split('.')].pop();
                        if (isImage) {
                            filePath = 'images';
                        }
                        return `static/${filePath}/[name].[hash].[ext]`;
                    }, // 资源文件像 字体，图片等
                    manualChunks(id) {
                        // 将node_modules的扩展单独进行打包
                        if (id.includes('node_modules')) {
                            return id.toString().split('node_modules/')[1].split('/')[0].toString();
                        }
                    }
                }
            }
        }
}});

### What is expected?

able to optimize images

### What is actually happening?

<img width="942" alt="image" src="https://github.com/unplugin/unplugin-imagemin/assets/22415838/1d741793-5b78-46b1-80a6-81e4e2d96126">
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/*******/node_modules/.pnpm/ora@6.3.0/node_modules/ora/index.js from /Users/*******/node_modules/.pnpm/unplugin-imagemin@0.5.18/node_modules/unplugin-imagemin/dist/chunk-UFJ5C3UB.js not supported.

### System Info

```shell
mac bookpro  m3
```

**Comment by ErKeLost** [comment]
The latest version solves all problems
