### ISSUE TITLE
[Feature Request] Support for compression of svg files

### ISSUE THREAD

**Issue by FatehAK** [unplugin/unplugin-imagemin#13]
Currently we are using `vite-plugin-imagemin` to compress images and svg files. We would like to switch to this package since it seems promising and is up to date. 

Are there are any plans to include svgo for compressing svg files?

**Comment by ErKeLost** [comment]
Thank you very much. Svgo will be online soon.

**Comment by ErKeLost** [comment]
Svg format is already supported and optimization is being tested
