### ISSUE TITLE
Should use original image compressed image is larger

### ISSUE THREAD

**Issue by maaarghk** [unplugin/unplugin-imagemin#15]
[map.png within image.tar.gz](https://github.com/ErKeLost/unplugin-imagemin/files/10273323/image.tar.gz) goes from 15692 bytes to 17003 bytes after sharp is run. you could check for newSize > oldSize [here](https://github.com/ErKeLost/unplugin-imagemin/blob/e40ae824c642fa3e2b62538381172809a9bf351b/src/core/context.ts#L289) and put the original file in the bundle instead

**Comment by ErKeLost** [comment]
有的情况下，在压缩png格式图片会 sharp 会导致图片压缩变大，这应该取决于您的options配置， 我应该需要判断一下 如果当前配置压缩之后 size 大于 origin size 应该拒绝压缩

**Comment by ErKeLost** [comment]
In some cases, when compressing a picture in png format, sharp will cause the image compression to become larger, which should depend on your options configuration. I should decide that compression should be rejected if size is greater than origin size after the current configuration is compressed.
