### ISSUE TITLE
The plugin doesn't seem to work. TypeError: fetch failed.

### ISSUE THREAD

**Issue by liv3rise** [unplugin/unplugin-imagemin#17]
Hey! I'm looking for plugins to optimize and convert images to webp and found yours but it doesn't seem to work. 🙁

```
> vite build

(node:15024) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:9273:35)
      at schemeFetch (node:internal/deps/undici/undici:10610:18)
      at node:internal/deps/undici/undici:10483:26
      at mainFetch (node:internal/deps/undici/undici:10500:11)
      at fetching (node:internal/deps/undici/undici:10457:7)
      at Agent.fetch2 (node:internal/deps/undici/undici:10337:20)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (C:\Users\lvrs\Projects\vite-test\node_modules\@squoosh\lib\build\index.js:28:11469)
      at createWasm (C:\Users\lvrs\Projects\vite-test\node_modules\@squoosh\lib\build\index.js:28:12079) {
    [cause]: undefined
  }
}
```
Can this be fixed?

**Comment by ErKeLost** [comment]
Thank you for your use. Can you provide a demo repository in github? let me see what the problem is.

**Comment by liv3rise** [comment]
> Thank you for your use. Can you provide a demo repository in github? let me see what the problem is.

Ok, so...

1. I created a Vanilla project with `npm create vite@latest`

2. Then added your plugin with `npm i unplugin-imagemin -D`

3. After that I edited vite.config.js and added a test image to index.html.

4. I ran `npm run dev` or `npm run build` and get the same error.

Here is the repository:
https://github.com/liv3rise/imagemin-test

**Comment by ErKeLost** [comment]
> > Thank you for your use. Can you provide a demo repository in github? let me see what the problem is.
> 
> Ok, so...
> 
> 1. I created a Vanilla project with `npm create vite@latest`
> 2. Then added your plugin with `npm i unplugin-imagemin -D`
> 3. After that I edited vite.config.js and added a test image to index.html.
> 4. I ran `npm run dev` or `npm run build` and get the same error.
> 
> Here is the repository: https://github.com/liv3rise/imagemin-test

The demo you gave does not reproduce the problem. When the vite reloads the module, it does not recognize the resources imported by index.html and cannot find other picture modules in your demo.
![image](https://user-images.githubusercontent.com/66500121/214222758-16c1401d-0009-4ae8-95a7-d0bc29f6fb8a.png)
And then I tried the conversion process myself.
- vite.config.js 
![image](https://user-images.githubusercontent.com/66500121/214223053-d9ba6d8d-9781-44e5-b71d-68c5f143adb2.png)
- build assets
![image](https://user-images.githubusercontent.com/66500121/214222976-060b6587-59a4-4698-ba02-858b28edc26b.png)
At present, there is nothing wrong with my test. You can fock the warehouse, then run it locally and run it in the playground package to check the results.
1.  pnpm install
2.  pnpm bootstrap
3.  cd playground
4.  pnpm build

If you have not installed pnpm, you can first `npm install pnpm -g`

There may be a real problem, because the current code is not very perfect, the search methods of some modules need to be strengthened, can you provide a more detailed demo?

**Comment by ErKeLost** [comment]
![image](https://user-images.githubusercontent.com/66500121/214223990-9048da3f-cd6f-4f69-b252-f62b445a41cf.png)

Because of the current problem when loading the module, unplugin-imagemin provides two packaging methods that you can use ` beforeBundle: false,`  It is no problem to get all the packaged resources to be compressed after building. You can try this property again.

**Comment by liv3rise** [comment]
> > > Thank you for your use. Can you provide a demo repository in github? let me see what the problem is.
> > 
> > Ok, so...
> > 
> > 1. I created a Vanilla project with `npm create vite@latest`
> > 2. Then added your plugin with `npm i unplugin-imagemin -D`
> > 3. After that I edited vite.config.js and added a test image to index.html.
> > 4. I ran `npm run dev` or `npm run build` and get the same error.
> > 
> > Here is the repository: https://github.com/liv3rise/imagemin-test
> 
> The demo you gave does not reproduce the problem. When the vite reloads the module, it does not recognize the resources imported by index.html and cannot find other picture modules in your demo.
> 
> ![image](https://user-images.githubusercontent.com/66500121/214222758-16c1401d-0009-4ae8-95a7-d0bc29f6fb8a.png)
> And then I tried the conversion process myself.
> - vite.config.js 
> ![image](https://user-images.githubusercontent.com/66500121/214223053-d9ba6d8d-9781-44e5-b71d-68c5f143adb2.png)
> - build assets
> ![image](https://user-images.githubusercontent.com/66500121/214222976-060b6587-59a4-4698-ba02-858b28edc26b.png)
> At present, there is nothing wrong with my test. You can fock the repository , then run it locally and run it in the playground package to check the results.
> 
> 1.  pnpm bootstrap
> 2.  cd playground
> 3.  pnpm build
> 
> If you have not installed pnpm, you can first `npm install pnpm -g`
> 
> There may be a real problem, because the current code is not very perfect, the search methods of some modules need to be strengthened, Or you can provide a more detailed demo.

I don't know what more detailed demo to present to you.  I have vanilla projects, no frameworks, just pure HTML/CSS/JS and I want all the images in the project to just convert from png/jpg to webp.  Maybe I'm just dumb and don't understand what exactly this plugin does, it's not designed for that?

**Comment by ErKeLost** [comment]
![image](https://user-images.githubusercontent.com/66500121/214225777-11886ef9-7542-4852-81a2-2befe5368c4c.png)

You are trying to use this set of configuration files.

```ts
    imagemin({
      // Default mode squoosh. support squoosh and sharp
      mode: 'squoosh',
      beforeBundle: false,
      // Default configuration options for compressing different pictures
      compress: {
        jpg: {
          quality: 0,
        },
        jpeg: {
          quality: 70,
        },
        png: {
          quality: 70,
        },
        webp: {
          quality: 70,
        },
      },
      // The type of picture converted after the build
      conversion: [
        { from: 'png', to: 'webp' },
        { from: 'jpg', to: 'webp' },
        { from: 'jpeg', to: 'webp' },
      ]
    })
```

**Comment by liv3rise** [comment]
> * At present, there is nothing wrong with my test. You can fock the repository , then run it locally and run it in the playground package to check the results.
> 
> 1. pnpm bootstrap
> 2. cd playground
> 3. pnpm build
> 
> If you have not installed pnpm, you can first `npm install pnpm -g`

Very strange... I installed pnpm like you said and tried to run `pnpm build` in your playground but I still get the same error...

```
> playground@0.0.0 build C:\Users\lvrs\Projects\unplugin-imagemin\playground
> vue-tsc && vite build

(node:7564) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
      at fetching (node:internal/deps/undici/undici:10457:7)
      at Agent.fetch2 (node:internal/deps/undici/undici:10337:20)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at instantiateAsync (C:\Users\lvrs\Projects\unplugin-imagemin\node_modules\.pnpm\@squoosh+lib@0.4.0\node_modules\@squoosh\lib\build\index.js:28:11469)
      at createWasm (C:\Users\lvrs\Projects\unplugin-imagemin\node_modules\.pnpm\@squoosh+lib@0.4.0\node_modules\@squoosh\lib\build\index.js:28:12079) {
    [cause]: undefined
  }
}

Node.js v18.12.1 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by ErKeLost** [comment]
I know why its not work because squoosh doesn't support node18. 
I'll fix the error report of sharp for you now. I'll send a version right away and you can use it.

**Comment by liv3rise** [comment]
> Do you know nvm? you can easily manage your node version and switch it at any time.

Okay, thanks.  Yes, I know about nvm.  I will try this in 4-5 hours as I have to leave home for a while now.

**Comment by ErKeLost** [comment]
> > Do you know nvm? you can easily manage your node version and switch it at any time.
> 
> Okay, thanks. Yes, I know about nvm. I will try this in 4-5 hours as I have to leave home for a while now.

I'm very sorry, this is my problem, I should tell you in readme that these problems are really happy to help you solve the problem.

**Comment by liv3rise** [comment]
> I'm very sorry, this is my problem, I should tell you in readme that these problems are really happy to help you solve the problem.

No problem, don't worry 😊
Thanks for your help

**Comment by liv3rise** [comment]
> > > Do you know nvm? you can easily manage your node version and switch it at any time.
> > 
> > 
> > Okay, thanks. Yes, I know about nvm. I will try this in 4-5 hours as I have to leave home for a while now.
> 
> I'm very sorry, this is my problem, I should tell you in readme that these problems are really happy to help you solve the problem.

With NodeJS 16.9.1 this works well. But I have an additional question. Is there any way to change the image URL on build to match the new .webp format?

For example, I have an image in src/img/example.png and in index.html there is an element `<img src="src/img/example.png" />`. After the build, example.png is converted to .webp, but in index.html the image address still refers to .png. Is there a way to fix this?

**Comment by ErKeLost** [comment]
> > 非常抱歉，这是我的问题，我应该在readme中告诉你，这些问题真的很乐意帮助你解决问题。
> 
> 使用 NodeJS 16.9.1 这很有效。但我还有一个问题。有什么方法可以更改构建时的图像 URL 以匹配新的 .webp 格式？
> 
> 例如，我在 src/img/example.png 中有一个图像，在 index.html 中有一个 element `<img src="src/img/example.png" />`。构建后example.png转为.webp，但index.html中图片地址仍为.png。有没有办法来解决这个问题？

Because if you use html alone, html will not be packaged, but can only modify pack js module. I will see if I can help you by converting html.

**Comment by ErKeLost** [comment]
> 



> > > 非常抱憾，这是我的问题，我应该在自述文件中告诉你，这些问题真的很有趣帮助你解决问题。
> > 
> > 
> > 使用 NodeJS 16.9.1 这很有效。但我还有一个问题。有什么方法可以更改构建时的图像 URL 以匹配新的 .webp 格式？
> > 比如，我在src/img/example.png中有一个图像，在index.html中有一个element `<img src="src/img/example.png" />`。构建后example.png转为.webp，但index.html中图片地址仍然为.png。有没有办法来解决这个问题？
> 
> 因为单独使用html的话，html不会被打包，只能修改pack js模块。Currently, only js and other asset modules can be built, and index.html has not taken into account, 我会看看我是否可以通过转换 html 来帮助您。

**Comment by ErKeLost** [comment]
> > 
> 
> > > > 非常抱憾，这是我的问题，我应该在自述文件中告诉你，这些问题真的很有趣帮助你解决问题。
> > > 
> > > 
> > > 使用 NodeJS 16.9.1 这很有效。但我还有一个问题。有什么方法可以更改构建时的图像 URL 以匹配新的 .webp 格式？
> > > 比如，我在src/img/example.png中有一个图像，在index.html中有一个element `<img src="src/img/example.png" />`。构建后example.png转为.webp，但index.html中图片地址仍然为.png。有没有办法来解决这个问题？
> > 
> > 
> >

**Comment by ErKeLost** [comment]
> > I'm very sorry, this is my problem, I should tell you in readme that these problems are really happy to help you solve the problem.
> 
> With NodeJS 16.9.1 this works well. But I have an additional question. Is there any way to change the image URL on build to match the new .webp format?
> 
> For example, I have an image in src/img/example.png and in index.html there is an element `<img src="src/img/example.png" />`. After the build, example.png is converted to .webp, but in index.html the image address still refers to .png. Is there a way to fix this?

Because if you use html alone, html will not be packaged, you can only modify the pack js module. Currently, only js and other asset modules can be built, and index.html has not taken into account, you can actually use the framework to introduce pictures into the js module to solve this problem. The current code logic is to solve the problem in the js module.

**Comment by ErKeLost** [comment]
> > > I'm very sorry, this is my problem, I should tell you in readme that these problems are really happy to help you solve the problem.
> > 
> > 
> > With NodeJS 16.9.1 this works well. But I have an additional question. Is there any way to change the image URL on build to match the new .webp format?
> > For example, I have an image in src/img/example.png and in index.html there is an element `<img src="src/img/example.png" />`. After the build, example.png is converted to .webp, but in index.html the image address still refers to .png. Is there a way to fix this?
> 
> Because if you use html alone, html will not be packaged, you can only modify the pack js module. 

Currently, only js and other asset modules can be built, and index.html has not taken into account, 

you can actually use the framework to introduce pictures into the js module to solve this problem. The current code logic is to solve the problem in the js module.

**Comment by ErKeLost** [comment]
Or if there's any way I can contact you, I can help you with how to use it.

**Comment by liv3rise** [comment]
> Because if you use html alone, html will not be packaged, you can only modify the pack js module. Currently, only js and other asset modules can be built, and index.html has not taken into account, you can actually use the framework to introduce pictures into the js module to solve this problem. The current code logic is to solve the problem in the js module.

Okay, I got it

> Or if there's any way I can contact you, I can help you with how to use it. in other framework

I try to learn as much as possible on my own, so don't need to yet.  If I need a framework, I'll try to figure it out myself first, so I'll learn more. But here's my discord just in case: liv3rise#5010.  Maybe one day we'll need to contact. 😅

> I will also do a set of logic for you to convert pictures in html. It's coming.

Do you mean that you are working on this logic in your plugin?  If so, that would be really cool, I'll be looking forward to it. 🥰

And again - thanks for everything, for answering and helping.  I appreciate it. ❤️

**Comment by ErKeLost** [comment]
> > Because if you use html alone, html will not be packaged, you can only modify the pack js module. Currently, only js and other asset modules can be built, and index.html has not taken into account, you can actually use the framework to introduce pictures into the js module to solve this problem. The current code logic is to solve the problem in the js module.
> 
> Okay, I got it
> 
> > Or if there's any way I can contact you, I can help you with how to use it. in other framework
> 
> I try to learn as much as possible on my own, so don't need to yet. If I need a framework, I'll try to figure it out myself first, so I'll learn more. But here's my discord just in case: liv3rise#5010. Maybe one day we'll need to contact. 😅
> 
> > I will also do a set of logic for you to convert pictures in html. It's coming.
> 
> Do you mean that you are working on this logic in your plugin? If so, that would be really cool, I'll be looking forward to it. 🥰
> 
> And again - thanks for everything, for answering and helping. I appreciate it. ❤️

I added you as a discord

**Comment by cnyxq** [comment]
v16.18.2 is supported
