### ISSUE TITLE
🐛 [Bug]: Cannot find module 'eslint-define-config'

### ISSUE THREAD

**Issue by hxj9102** [unplugin/unplugin-imagemin#2]
![203309103-a5ed45e0-fd39-4ccf-8bd7-b9097e056cd2](https://user-images.githubusercontent.com/58357112/203310564-17536b0b-ec1a-4da0-81e3-bee3877a454e.png)
![203309218-d4fc2baa-04b7-46cb-a381-ae8cbb2b54c9](https://user-images.githubusercontent.com/58357112/203310588-df53ebe2-f6bc-44c7-8aa7-280cba7c290e.png)
![203309276-c5c1607a-290a-421f-b943-47c4391a3dea](https://user-images.githubusercontent.com/58357112/203310599-03b58217-0c85-4db7-9620-c23e967e9924.png)

maybe dependencies should add eslint-define-config in eslint-config-relaxed-base package.json

**Comment by ErKeLost** [comment]
It is true that due to the lack of introduction of finding a package, the dependency has been repaired and needs to be upgraded. Thank you for asking questions.

**Comment by ErKeLost** [comment]
At present, the type has not been fixed and the center of gravity is still on transform.

**Comment by hxj9102** [comment]
I try to solve the problem.

**Comment by ErKeLost** [comment]
Now that I think about two situations, we can add a Wechat to discuss them.     number  y1256029807
