### ISSUE TITLE
support public assets

### ISSUE THREAD

**Issue by higuaifan** [unplugin/unplugin-imagemin#65]
### What problem does this feature solve?

When images are located in the '/public' directory, Vite automatically copies them to the output directory, typically named 'dist'. However, the 'unplugin-imagemin' package fails to load and compress these images as intended.

### What does the proposed API look like?

we need load public files and compress them 🌹

**Comment by ErKeLost** [comment]
copy that

**Comment by ErKeLost** [comment]
already supported
