### ISSUE TITLE
transformed error when import the same image

### ISSUE THREAD

**Issue by lzj12530** [unplugin/unplugin-imagemin#66]
### Steps to reproduce

// vite.config.js
1. enable conversion just like this.
      conversion: [
        { from: "png", to: "webp" },
        { from: "jpeg", to: "png" },
      ]

2. two css file import the same image
// css file 1
.c1 {
background-image: url(./test.png);
}
// css file 2
.c2{
background-image: url(./test.png);
}

3. after build the image has been transformed to "test.webp" , and the first file has changed the name,but another not.
.c1 {
background-image: url(./test.webp);
}

.c2{
background-image: url(./test.png);
}

### What is expected?

all of the css file should be changed

### What is actually happening?

 the first file has changed the name, but the rest is not.
we got 404 when start the build

**Comment by ErKeLost** [comment]
So far, only the first useless replaceAll will be replaced. I'll fix this problem tonight.

**Comment by ErKeLost** [comment]
Thank you for your question. The problem has been solved.

**Comment by lzj12530** [comment]
Thank you.

**Comment by ErKeLost** [comment]
> Thank you.

you're welcome
