### ISSUE TITLE
最新版本build报错，sharp...is not a function

### ISSUE THREAD

**Issue by yinhaogt** [unplugin/unplugin-imagemin#67]
### Steps to reproduce

![image](https://github.com/unplugin/unplugin-imagemin/assets/53333420/f6e9416a-4c79-46d2-b7fa-22f27dd8f8d3)

### What is expected?

修复bug，正常build，退回到0.5.3后build正常

### What is actually happening?

![image](https://github.com/unplugin/unplugin-imagemin/assets/53333420/f6e9416a-4c79-46d2-b7fa-22f27dd8f8d3)

### System Info

```shell
macOS 13 M1pro
```

**Comment by ErKeLost** [comment]
可以提供一个demo 么 我本地复现不出来

**Comment by null0034** [comment]
你看看是不是你的配置项中，对于格式的转换没有对应上你的图片格式，比如你的图片格式是 .png 然而在
`conversion: [
                { from: 'jpeg', to: 'webp' },
                { from: 'JPG', to: 'jpeg' },
            ]`
中没有` { from: 'png', to: 'jpeg' },`这一个配置，这样它也报这个错误

**Comment by ErKeLost** [comment]
> 你看看是不是你的配置项中，对于格式的转换没有对应上你的图片格式，比如你的图片格式是 .png 然而在 `conversion: [ { from: 'jpeg', to: 'webp' }, { from: 'JPG', to: 'jpeg' }, ]` 中没有` { from: 'png', to: 'jpeg' },`这一个配置，这样它也报这个错误

我修复一下这个问题

**Comment by ErKeLost** [comment]
我起了一个demo 按照你的配置 还是复现不出来 你node 什么版本 能提供一个 demo 么

> > 你看看是不是你的配置项中，对于格式的转换没有对应上你的图片格式，比如你的图片格式是 .png 然而在 `conversion: [ { from: 'jpeg', to: 'webp' }, { from: 'JPG', to: 'jpeg' }, ]` 中没有` { from: 'png', to: 'jpeg' },`这一个配置，这样它也报这个错误
> 
> 我修复一下这个问题

我起了一个demo 按照你的配置 还是复现不出来 你node 什么版本 能提供一个 demo 么

**Comment by yinhaogt** [comment]
> 可以提供一个demo 么 我本地复现不出来 是 sharp 和 squoosh 都报错么？ 都报这个 sharp 的错

我测了最近的几个版本，是从0.5.5开始的，0.5.4没有问题，但是我新起的demo没有问题！所以我现在不知道是我项目资源的问题还是代码的问题，项目不好给你测，我先自己试一试，发现了再来reply

**Comment by ErKeLost** [comment]
> > 可以提供一个demo 么 我本地复现不出来 是 sharp 和 squoosh 都报错么？ 都报这个 sharp 的错
> 
> 我测了最近的几个版本，是从0.5.5开始的，0.5.4没有问题，但是我新起的demo没有问题！所以我现在不知道是我项目资源的问题还是代码的问题，项目不好给你测，我先自己试一试，发现了再来reply

好的好的 我也起了 demo 按照你的配置 也没有问题

**Comment by ErKeLost** [comment]
> > > 可以提供一个demo 么 我本地复现不出来 是 sharp 和 squoosh 都报错么？ 都报这个 sharp 的错
> > 
> > 
> > 我测了最近的几个版本，是从0.5.5开始的，0.5.4没有问题，但是我新起的demo没有问题！所以我现在不知道是我项目资源的问题还是代码的问题，项目不好给你测，我先自己试一试，发现了再来reply
> 
> 好的好的 我也起了 demo 按照你的配置 也没有问题 是一下修改一下 beforeBundle 呢

**Comment by yinhaogt** [comment]
> > > 可以提供一个demo 么 我本地复现不出来 是 sharp 和 squoosh 都报错么？ 都报这个 sharp 的错
> > 
> > 
> > 我测了最近的几个版本，是从0.5.5开始的，0.5.4没有问题，但是我新起的demo没有问题！所以我现在不知道是我项目资源的问题还是代码的问题，项目不好给你测，我先自己试一试，发现了再来reply
> 
> 好的好的 我也起了 demo 按照你的配置 也没有问题 试一下修改一下 beforeBundle 呢

beforeBundle可以的

**Comment by Miofly** [comment]
我遇到了相同的问题，node 版本 v18.15.0，我把插件降低到0.5.4后此问题没有了

**Comment by ErKeLost** [comment]
> 我遇到了相同的问题，node 版本 v18.15.0，我把插件降低到0.5.4后此问题没有了

可以提供一个 demo 么 我复现不出来

**Comment by Ttou** [comment]
@ErKeLost 示例项目：https://github.com/Ttou/imagemin-issue

**Comment by ErKeLost** [comment]
> @ErKeLost 示例项目：https://github.com/Ttou/imagemin-issue

okok 感谢 我去试一下

**Comment by ErKeLost** [comment]
> @ErKeLost 示例项目：https://github.com/Ttou/imagemin-issue

你是 windows 是么 那可能还是 windows 有问题等我找个windows 试一下 mac 应该是好用的 
<img width="685" alt="image" src="https://github.com/unplugin/unplugin-imagemin/assets/66500121/1160b845-cc57-4e0e-a33a-7ec6e5ea6962">

**Comment by Ttou** [comment]
我是 mac m1，打包报错
![image](https://github.com/unplugin/unplugin-imagemin/assets/4298437/512a5454-6e28-4252-a74e-0054335048b5)

**Comment by ErKeLost** [comment]
好奇怪 我这个 build 就好使 node 什么版本

**Comment by Ttou** [comment]
16.20.2

**Comment by ErKeLost** [comment]
我还是复现不出来 还是好使 好奇怪 这个问题好多人遇到了 我就是复现不出来  😭😭

**Comment by Ttou** [comment]
@ErKeLost 我发现是隐藏文件在起作用。示例项目在本地有个隐藏文件 `.DS_Store`，插件在处理该文件时报错了

![image](https://github.com/unplugin/unplugin-imagemin/assets/4298437/021372d0-ffde-4938-a23d-0953e98c924a)

**Comment by ErKeLost** [comment]
@Ttou  okok 我懂了 这个文件没有后缀 拿不到 ext 对不上 imageModule 所以就报错了 我改一下 感谢

**Comment by ErKeLost** [comment]
v0.5.11 问题已解决
