### ISSUE TITLE
Running app after installing plugin causes an error

### ISSUE THREAD

**Issue by aimen08** [unplugin/unplugin-imagemin#70]
### Steps to reproduce

`yarn add unplugin-imagemin@latest -D`
`yarn start` or `yarn build`

### What is expected?

run normally

### What is actually happening?

![image](https://github.com/unplugin/unplugin-imagemin/assets/32209952/e51d75ec-4cb7-4e22-bb40-e4931706c4e3)

### System Info

```shell
window 11
vite 4.4.5
unplugin-imagemin 0.5.9
yarn
```

**Comment by ErKeLost** [comment]
hi~ , Can you provide a demo? it looks like there is an error loading ora.

**Comment by aimen08** [comment]
yeah sure , https://www.loom.com/share/4c14baddac144d5da7f00b50ec8ac117?sid=46727a04-dcaa-4cb1-adf4-f178f0f4c835

**Comment by ErKeLost** [comment]
> yeah sure , https://www.loom.com/share/4c14baddac144d5da7f00b50ec8ac117?sid=46727a04-dcaa-4cb1-adf4-f178f0f4c835
> 
> Edit : i'm using node v16.20.2 Edit2: same problem with 18.16.1

thanks！Can you provide your complete packageJson file because I can't reproduce the problem after I try?

**Comment by aimen08** [comment]
`{
  "name": "test",
  "homepage": "https://test.com",
  "version": "1.28.2",
  "private": true,
  "scripts": {
    "start": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview",
    "lint": "run-s eslint stylelint",
    "lint:fix": "run-s eslint:fix stylelint:fix",
    "eslint": "eslint src packages/search",
    "eslint:fix": "npm run eslint -- --fix --ext .js,.jsx,.ts,.tsx",
    "stylelint": "stylelint \"src/styles/**/*.scss\" \"src/**/*.module.scss\"",
    "stylelint:fix": "npm run stylelint -- --fix",
    "test": "craco test --testPathIgnorePatterns=src/@design-library",
    "test:e2e": "cypress run --env excludeTags=visual",
    "test:e2e:visual": "cypress run --env type=actual,tags=visual",
    "test:e2e:visual:base": "cypress run --env type=base,tags=visual --config screenshotsFolder=cypress/snapshots/base",
    "test:e2e:all": "cypress run --env type=actual",
    "cy:open": "cypress open --env excludeTags=visual",
    "cy:open:visual": "cypress open --env type=actual,tags=visual",
    "cy:open:all": "cypress open --env type=actual",
    "cy:run": "cypress run",
    "storybook": "start-storybook -p 6006",
    "storybook:build": "build-storybook ",
    "list-routes": "cross-env NODE_PATH=./src ts-node bin/list-routes.js"
  },
  "resolutions": {
    "moment": "2.24.0"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "dependencies": {
    "@hapi/joi": "^17.1.1",
    "@hookform/resolvers": "^1.3.7",
    "@popperjs/core": "^2.11.4",
    "@reach/tooltip": "^0.13.0",
    "@react-pdf/renderer": "^3.1.8",
    "@segment/analytics-next": "^1.53.2",
    "@tanstack/react-virtual": "^3.0.0-beta.18",
    "@uppy/core": "^1.20.1",
    "@uppy/dashboard": "^1.21.1",
    "@uppy/react": "^1.12.2",
    "@uppy/webcam": "^1.8.13",
    "@uppy/xhr-upload": "^1.7.5",
    "abortcontroller-polyfill": "^1.7.3",
    "clsx": "^1.1.1",
    "cross-fetch": "^3.1.4",
    "dayjs": "^1.11.7",
    "file-saver": "^2.0.5",
    "flag-icons": "^6.11.0",
    "fslightbox-react": "file:packages/fslightbox-react-pro-1.1.1-2.tgz",
    "leaflet": "^1.7.1",
    "linkifyjs": "^2.1.9",
    "lodash": "^4.17.21",
    "parse-price": "^1.1.8",
    "prop-types": "^15.8.0",
    "query-string": "^6.14.1",
    "rc-collapse": "^1.11.8",
    "rc-table": "^7.33.1",
    "react": "^18.2.0",
    "react-click-away-listener": "^1.6.3",
    "react-content-loader": "^4.3.4",
    "react-day-picker": "^7.4.10",
    "react-dom": "^18.2.0",
    "react-facebook-login": "^4.1.1",
    "react-feather": "^2.0.10",
    "react-google-login": "^5.2.2",
    "react-google-recaptcha": "^2.0.1",
    "react-gtm-module": "^2.0.11",
    "react-helmet": "^5.2.1",
    "react-hook-form": "^6.15.8",
    "react-input-mask": "^2.0.4",
    "react-localization": "^1.0.17",
    "react-modal": "^3.14.4",
    "react-paginate": "^8.2.0",
    "react-popper": "^2.2.5",
    "react-portal": "^4.2.1",
    "react-query": "^2.26.4",
    "react-query-devtools": "^2.6.3",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.6",
    "react-responsive": "^9.0.2",
    "react-router-dom": "^5.3.0",
    "react-select": "^3.2.0",
    "react-sortablejs": "^6.0.0",
    "react-spinners": "^0.6.1",
    "react-sticky-el": "^2.0.9",
    "react-swipeable-views": "0.13.9",
    "react-text-truncate": "^0.19.0",
    "redux": "^4.1.2",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.4.1",
    "reselect": "^4.1.5",
    "smoothscroll-polyfill": "^0.4.4",
    "sortablejs": "^1.15.0",
    "sweetalert2": "^11.7.27",
    "swiper": "^8.4.2",
    "wechalet-search": "file:packages/search",
    "yup": "^0.28.1",
    "zxcvbn": "^4.4.2"
  },
  "devDependencies": {
    "@cypress/webpack-preprocessor": "^5.16.3",
    "@faker-js/faker": "^8.0.2",
    "@storybook/addon-actions": "^6.4.19",
    "@storybook/addon-docs": "^6.4.19",
    "@storybook/addon-essentials": "^6.4.19",
    "@storybook/addon-knobs": "^6.4.0",
    "@storybook/addon-links": "^6.4.19",
    "@storybook/addon-viewport": "^6.4.19",
    "@storybook/node-logger": "^6.4.19",
    "@storybook/preset-create-react-app": "^3.2.0",
    "@storybook/react": "^6.4.19",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.1",
    "@testing-library/user-event": "^7.1.2",
    "@types/jest": "^26.0.24",
    "@types/lodash": "^4.14.180",
    "@types/prop-types": "^15.7.4",
    "@types/query-string": "^6.3.0",
    "@types/react": "^18.2.9",
    "@types/react-dom": "^18.2.4",
    "@types/react-redux": "^7.1.23",
    "@types/react-router-dom": "^5.3.3",
    "@types/sortablejs": "^1.10.7",
    "@vitejs/plugin-react": "^4.0.3",
    "cli-color": "^2.0.1",
    "cross-env": "^7.0.3",
    "cypress": "^13.2.0",
    "cypress-iframe": "^1.0.1",
    "cypress-react-selector": "^3.0.0",
    "cypress-visual-regression": "^3.0.0",
    "cypress-vite": "^1.4.2",
    "dotenv": "^8.6.0",
    "eslint": "^8.45.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.3",
    "glob": "^7.2.0",
    "jest": "^29.5.0",
    "npm-run-all": "^4.1.5",
    "redux-devtools-extension": "^2.13.9",
    "sass": "^1.49.9",
    "stylelint": "^13.13.1",
    "stylelint-config-sass-guidelines": "^7.1.0",
    "ts-node": "^9.1.1",
    "typescript": "5.0.2",
    "unplugin-imagemin": "0.5.9",
    "vite": "^4.4.5",
    "vite-plugin-checker": "^0.6.2",
    "vite-plugin-handlebars": "^1.6.0",
    "vite-plugin-svgr": "^3.2.0",
    "vite-tsconfig-paths": "^4.2.0",
    "xml-js": "^1.6.11"
  }
}`

**Comment by aimen08** [comment]
i found [this](https://github.com/sindresorhus/ora/issues/189) , which is caused by ora like you mentiond and ora downgrade seems like the solution , but the weird thing is why is it not happening to others.

**Comment by ErKeLost** [comment]
I know why. I think you set up `type: commonjs` in package.json.

**Comment by aimen08** [comment]
ohh thank you that fixed , i forgot altogether about that , thank you again for this awesome plugin.

**Comment by ErKeLost** [comment]
you a welcome

**Comment by aimen08** [comment]
> you are welcome thanks for use it

quick question do you know a way to add public folder to the build step so the images in it can be converted and optimized

**Comment by ErKeLost** [comment]
Public dir will automatically perform compression builds, and there may be some problems for the time being. I will finish this function recently and I will let you know when I release it again.

**Comment by aimen08** [comment]
Okay thank you, I appreciate that
