### ISSUE TITLE
The plugin does not reduce images, does not convert them.

### ISSUE THREAD

**Issue by tuber84** [unplugin/unplugin-imagemin#71]
### Steps to reproduce

Installed via pnpm, all dependencies were installed, no errors.
- "pnpm build" does not produce any errors (screenshot).
- "pnpm dev" works great project available, all images are in place.
- Vite settings as you recommend, nothing extra.
- But nothing happens with the images (from the public/ folder) (they are not compressed, not converted).
![image](https://github.com/unplugin/unplugin-imagemin/assets/97830928/5629d9a7-c60a-409a-ad56-e448673d6919)

![image](https://github.com/unplugin/unplugin-imagemin/assets/97830928/869ac149-eb03-4728-a6a0-32b3424c0dbb)

_Where to look for the reason for such work?_

vite.config.js :

```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import imagemin from "unplugin-imagemin/vite";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    imagemin({
      // Default mode squoosh. support squoosh and sharp
      mode: "sharp",
      // Default configuration options for compressing different pictures
      compress: {
        jpg: {
          quality: 40,
        },
        jpeg: {
          quality: 40,
        },
        png: {
          quality: 70,
        },
        webp: {
          quality: 70,
        },
      },
      // The type of picture converted after the build
      conversion: [
        { from: "png", to: "jpeg" },
        { from: "jpeg", to: "webp" },
        { from: "jpg", to: "webp" },
      ],
    }),
  ],
});
```
package.json:
```
{
  "name": "vite_tets",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "devDependencies": {
    "unplugin-imagemin": "^0.5.9",
    "vite": "^4.4.5"
  },
  "dependencies": {
    "@vitejs/plugin-vue": "^4.3.4",
    "sharp": "^0.32.6"
  }
}
```

### What is expected?

the expectation is that images will be compressed and converted like a still from your video.
![image](https://github.com/unplugin/unplugin-imagemin/assets/97830928/7f227175-155b-413d-9563-e862595f53a2)

### What is actually happening?

moved the images to the root of the public folder

**Comment by ErKeLost** [comment]
Thank you for your use.

- The first point is that if you do not use pictures in the project, they will not be compressed. They are based on the loading module.

- The second point is that the automatic compression of public public file directories is still in progress, and you will soon have the effect you want.

You can use them in the project for the time being so that you can compress them. If you update this feature later, I will let you know as soon as possible.

**Comment by tuber84** [comment]
Еhanks for the prompt response.
I use images in a css file via `background-image: url(/public/example.jpeg)` and the plugin doesn’t “see” them, so do I need to use them via import in javascript? 
`import Image from 'example.jpg'`

**Comment by ErKeLost** [comment]
you can set `beforeBundle: false`  This method modifies the compressed image in the final build file

**Comment by tuber84** [comment]
Thanks for helping a beginner, I tried your solution and nothing changed.


vite.config.js:
```import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import imagemin from "unplugin-imagemin/vite";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    imagemin({
      // Default mode squoosh. support squoosh and sharp
      mode: "sharp",
      conversion: [],
      beforeBundle: false,
      cache: false,
      compress: {
        jpg: {
          quality: 70,
        },
        jpeg: {
          quality: 70,
        },
        png: {
          quality: 70,
        },
        webp: {
          quality: 70,
        },
      },
    }),
  ],
});
```
- there is a proposal for a project, sketch out a simple sandbox project (many plugins provide such examples), where everything works (the simplest one without frameworks).

**Comment by ErKeLost** [comment]
Thank you for your advice. I'll provide an example of this and solve your problem. I'm going to try to do a sandbox now.

**Comment by ErKeLost** [comment]
https://stackblitz.com/edit/vitejs-vite-mgrkkb?file=playground%2Fpackage.json

I made an online link. You can try cd/playground & & pnpm build.

It may be because the picture exists in the public directory, but the current plugin may have done something wrong with public. I will fix this problem as soon as possible.

**Comment by tuber84** [comment]
Thank you, the project works in the sandbox, I downloaded it and will do “reverse engineering”.

**Comment by ErKeLost** [comment]
The problem with compression of loaded images in css has been solved
