### ISSUE TITLE
压缩失真问题

### ISSUE THREAD

**Issue by yinhaogt** [unplugin/unplugin-imagemin#73]
### Steps to reproduce

imagemin()直接调用

### What is expected?

正确压缩

### What is actually happening?

imagemin()直接调用就会导致颜色错误，有锯齿，只有某些图片会有问题
 imagemin({
      compress: {}
 })
这样就不失真，很奇怪

### System Info

```shell
macos13 m1pro
```

**Comment by ErKeLost** [comment]
按理说你写的这两种应该是一样的 有 demo 么 没有传option 会用 默认的一套

**Comment by yinhaogt** [comment]
主要是图片不方便给，等我有时间我调试一下看看

**Comment by ErKeLost** [comment]
> 主要是图片不方便给，等我有时间我调试一下看看

好的 我也看一下 是不是插件这边的问题

**Comment by ErKeLost** [comment]
试试最新版本 已经修复
